### ISSUE TITLE
Does this work on a docker?

### ISSUE THREAD

**Issue by wgv-rulak** [AydinAdn/MediaToolkit#100]
System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
Actual value was .
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at System.Collections.Generic.List`1.get_Item(Int32 index)
   at MediaToolkit.Engine.StartFFmpegProcess(EngineParameters engineParameters)

**Comment by JayeshC-96** [comment]
Any update on this issue?

**Comment by AydinAdn** [comment]
As far as I know, it shouldn't as is.

I need to test this out within a docker container and get back to you about this.

**Comment by AydinAdn** [comment]
You could try this out on your own by forking / cloning the library then debugging it within a container .

**Comment by TCGV** [comment]
I was able to resolve this issue by following these instructions:

> Hi LevH, 
> 
> I have the same issue recently.
> 
> After some try and errors, I found [avicap32.dll](https://web.archive.org/web/20211025210939/https://github.com/moiamond/docker-ffmpeg-base-windowsservercore/blob/master/System32/avicap32.dll) and [msvfw32.dll](https://web.archive.org/web/20211025210939/https://github.com/moiamond/docker-ffmpeg-base-windowsservercore/blob/master/System32/msvfw32.dll), dependency of ffmpeg, are missing in container.
> 
> They are in C:\Windows\System32\ (64bit) or C:\Windows\SysWOW64 (32bit)
> 
> Just copy them from host to container. ffmpeg can work again.
> 
> ---
> 
> My environment:
> 
> Host: Windows Server 2016 RTM
> 
> Container: microsoft/windowsservercore:10.0.14393.321
> 
> ---

Sources:

- https://superuser.com/questions/1742768/ffmpeg-on-windows-server-core-2022
- https://web.archive.org/web/20211025210939/https://social.msdn.microsoft.com/Forums/sqlserver/en-US/0c13bd1a-388f-48cf-a190-7259d39a080f/ffmpeg-doesnt-work-from-inside-a-container-but-works-on-the-host?forum=windowscontainers
